# Site settings
locale: "en-CA"
title: "Ryan A. Compton"
title_separator: "|"
description: "Ryan A. Compton is Professor of Economics at the University of Manitoba. Research in conflict and defence economics, development, institutions, and macroeconomics."
url: "https://ryanacompton.github.io"
baseurl: ""
repository: "RyanACompton/RyanACompton.github.io"

# Theme
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "air"
search: false

# Build settings
markdown: kramdown
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/
timezone: "America/Winnipeg"

include:
  - _pages

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Author profile
author:
  name: "Ryan A. Compton"
  avatar: "/assets/images/RAC.jpg"
  bio: "Professor of Economics, University of Manitoba"
  location: "Winnipeg, Canada"
  email: "ryan.compton@umanitoba.ca"
  links:
    - label: "University of Manitoba"
      icon: "fas fa-fw fa-university"
      url: "https://umanitoba.ca/arts/economics"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:ryan.compton@umanitoba.ca"
    - label: "CV"
      icon: "fas fa-fw fa-file-pdf"
      url: "/_pages/cv.pdf"
    - label: "Google Scholar"
      icon: "fas fa-fw fa-graduation-cap"
      url: "https://scholar.google.ca/citations?user=8PGw85QAAAAJ&hl=en&oi=ao"
    - label: "ORCID"
      icon: "fas fa-fw fa-id-card"
      url: "https://orcid.org/0000-0001-7752-3545"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/RyanACompton"

# Footer
footer:
  links:
    - label: "Google Scholar"
      icon: "fas fa-fw fa-graduation-cap"
      url: "https://scholar.google.ca/citations?user=8PGw85QAAAAJ&hl=en&oi=ao"
    - label: "ORCID"
      icon: "fas fa-fw fa-id-card"
      url: "https://orcid.org/0000-0001-7752-3545"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: false
      share: false
      related: false

  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/

tag_archive:
  type: liquid
  path: /tags/
